# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stxclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='ticker',
            field=models.CharField(default='ticker', max_length=10),
        ),
    ]
