# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stxclock', '0002_exchange_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
